export const background: string;
export const border: string;
export const hoverColorBorder: string;
export const pageGridBorder: string;
export const hoverPageGridBorder: string;
export const pageShadow: string;
export const showFlipbookBorder: string;
export const showFlipbookBackGround: string;
export const font: string;
